function direct(el,ns,local){return Array.from(el.childNodes).filter(n=>n.nodeType===1&&n.namespaceURI===ns&&n.localName===local)}
function firstDirect(el,ns,local){return direct(el,ns,local)[0]||null}
function wEl(doc,name){return doc.createElementNS(W,'w:'+name)}
function wpEl(doc,name){return doc.createElementNS(WP,'wp:'+name)}
function setW(el,name,val){el.setAttributeNS(W,'w:'+name,String(val))}
function rm(n){if(n&&n.parentNode)n.parentNode.removeChild(n)}
function pText(el){return Array.from(el.getElementsByTagNameNS(W,'t')).map(x=>x.textContent||'').join('')}
function visibleText(p){return pText(p).replace(/\u00a0/g,' ').trim()}
function ensurePPr(p){let x=firstDirect(p,W,'pPr');if(!x){x=wEl(p.ownerDocument,'pPr');p.insertBefore(x,p.firstChild)}return x}
function ensureRPr(r){let x=firstDirect(r,W,'rPr');if(!x){x=wEl(r.ownerDocument,'rPr');r.insertBefore(x,r.firstChild)}return x}
function removeDirect(parent,local){direct(parent,W,local).forEach(rm)}
function setJc(p,val){const pp=ensurePPr(p);let x=firstDirect(pp,W,'jc');if(!x){x=wEl(p.ownerDocument,'jc');pp.appendChild(x)}setW(x,'val',val)}
function setInd(p,first=420,left=null,right=null){const pp=ensurePPr(p);let x=firstDirect(pp,W,'ind');if(!x){x=wEl(p.ownerDocument,'ind');pp.appendChild(x)};if(first===null){x.removeAttributeNS(W,'firstLine');x.removeAttributeNS(W,'firstLineChars');x.removeAttributeNS(W,'hanging');x.removeAttributeNS(W,'hangingChars')}else{setW(x,'firstLine',first);x.removeAttributeNS(W,'firstLineChars');x.removeAttributeNS(W,'hanging');x.removeAttributeNS(W,'hangingChars')}if(left===null)x.removeAttributeNS(W,'left');else setW(x,'left',left);if(right===null)x.removeAttributeNS(W,'right');else setW(x,'right',right)}
function setSpacing(p){const pp=ensurePPr(p);let x=firstDirect(pp,W,'spacing');if(!x){x=wEl(p.ownerDocument,'spacing');pp.appendChild(x)}['before','after','beforeLines','afterLines'].forEach(a=>setW(x,a,0));setW(x,'line','240');setW(x,'lineRule','auto')}
function clearTabs(p){const pp=ensurePPr(p);removeDirect(pp,'tabs')}
function setBold(r,on=true){const rp=ensureRPr(r);removeDirect(rp,'b');removeDirect(rp,'bCs');if(on){rp.appendChild(wEl(r.ownerDocument,'b'));rp.appendChild(wEl(r.ownerDocument,'bCs'))}}
function setBlack(r){if(protectedRun(r)||r.getElementsByTagNameNS(W,'t').length===0)return;const rp=ensureRPr(r);let c=firstDirect(rp,W,'color');if(!c){c=wEl(r.ownerDocument,'color');rp.appendChild(c)}setW(c,'val','000000')}
function setSuper(r,on=true){const rp=ensureRPr(r);removeDirect(rp,'vertAlign');if(on){const x=wEl(r.ownerDocument,'vertAlign');setW(x,'val','superscript');rp.appendChild(x)}}
function setHighlight(r,val='yellow'){const rp=ensureRPr(r);removeDirect(rp,'highlight');const x=wEl(r.ownerDocument,'highlight');setW(x,'val',val);rp.appendChild(x)}
function clearHighlight(r){const rp=firstDirect(r,W,'rPr');if(rp)removeDirect(rp,'highlight')}
function hasAncestorNS(el,ns,locals){for(let n=el.parentNode;n;n=n.parentNode)if(n.namespaceURI===ns&&locals.includes(n.localName))return true;return false}
function protectedRun(r){return hasAncestorNS(r,M,['oMath','oMathPara'])||hasAncestorNS(r,W,['object','pict','drawing','fldSimple'])||direct(r,W,'fldChar').length||direct(r,W,'instrText').length}
function setFont(r,size=21){if(protectedRun(r)||r.getElementsByTagNameNS(W,'t').length===0)return;const rp=ensureRPr(r);let f=firstDirect(rp,W,'rFonts');if(!f){f=wEl(r.ownerDocument,'rFonts');rp.insertBefore(f,rp.firstChild)}['asciiTheme','hAnsiTheme','eastAsiaTheme','cstheme'].forEach(a=>f.removeAttributeNS(W,a));['ascii','hAnsi','eastAsia','cs'].forEach(a=>setW(f,a,'宋体'));let sz=firstDirect(rp,W,'sz');if(!sz){sz=wEl(r.ownerDocument,'sz');rp.appendChild(sz)}setW(sz,'val',size);let sc=firstDirect(rp,W,'szCs');if(!sc){sc=wEl(r.ownerDocument,'szCs');rp.appendChild(sc)}setW(sc,'val',size)}
function setParagraphFontDefault(p,size=21){const pp=ensurePPr(p);let rp=firstDirect(pp,W,'rPr');if(!rp){rp=wEl(p.ownerDocument,'rPr');pp.appendChild(rp)}let f=firstDirect(rp,W,'rFonts');if(!f){f=wEl(p.ownerDocument,'rFonts');rp.insertBefore(f,rp.firstChild)}['asciiTheme','hAnsiTheme','eastAsiaTheme','cstheme'].forEach(a=>f.removeAttributeNS(W,a));['ascii','hAnsi','eastAsia','cs'].forEach(a=>setW(f,a,'宋体'));let c=firstDirect(rp,W,'color');if(!c){c=wEl(p.ownerDocument,'color');rp.appendChild(c)}setW(c,'val','000000');let sz=firstDirect(rp,W,'sz');if(!sz){sz=wEl(p.ownerDocument,'sz');rp.appendChild(sz)}setW(sz,'val',size);let sc=firstDirect(rp,W,'szCs');if(!sc){sc=wEl(p.ownerDocument,'szCs');rp.appendChild(sc)}setW(sc,'val',size)}
function allRuns(p){return Array.from(p.getElementsByTagNameNS(W,'r'))}
function isSimpleRun(r){return !protectedRun(r)&&direct(r,W,'t').length>0&&Array.from(r.childNodes).every(n=>n.nodeType!==1||n.namespaceURI!==W||['rPr','t'].includes(n.localName))}
function cloneRunWithText(r,text){const d=r.ownerDocument,n=wEl(d,'r'),rp=firstDirect(r,W,'rPr');if(rp)n.appendChild(rp.cloneNode(true));const t=wEl(d,'t');if(/^\s|\s$/.test(text))t.setAttribute('xml:space','preserve');t.textContent=text;n.appendChild(t);return n}
function decorateMatchesInRun(r,re,styler){if(protectedRun(r))return 0;const text=Array.from(r.getElementsByTagNameNS(W,'t')).map(x=>x.textContent||'').join('');if(!text)return 0;re.lastIndex=0;const hits=[];let m;while((m=re.exec(text))){if(!m[0]){re.lastIndex++;continue}hits.push([m.index,m.index+m[0].length]);if(!re.global)break}if(!hits.length)return 0;if(!isSimpleRun(r)){if(hits.length===1&&hits[0][0]===0&&hits[0][1]===text.length){styler(r);return 1}return 0}let pos=0,count=0;for(const [a,b] of hits){if(a>pos)r.parentNode.insertBefore(cloneRunWithText(r,text.slice(pos,a)),r);const mr=cloneRunWithText(r,text.slice(a,b));styler(mr);r.parentNode.insertBefore(mr,r);count++;pos=b}if(pos<text.length)r.parentNode.insertBefore(cloneRunWithText(r,text.slice(pos)),r);rm(r);return count}
function isSimpleParagraph(p){return p.getElementsByTagNameNS(W,'fldChar').length===0&&p.getElementsByTagNameNS(W,'instrText').length===0&&p.getElementsByTagNameNS(W,'drawing').length===0&&p.getElementsByTagNameNS(W,'object').length===0&&p.getElementsByTagNameNS(W,'pict').length===0&&p.getElementsByTagNameNS(M,'oMath').length===0&&p.getElementsByTagNameNS(M,'oMathPara').length===0&&p.getElementsByTagNameNS(W,'hyperlink').length===0}
function cloneBaseRPr(p){const r=allRuns(p).find(x=>pText(x).length&&!protectedRun(x))||allRuns(p).find(x=>!protectedRun(x));const rp=r&&firstDirect(r,W,'rPr');return rp?rp.cloneNode(true):null}
function setPlainParagraphText(p,text){if(!isSimpleParagraph(p))return false;const base=cloneBaseRPr(p);Array.from(p.childNodes).forEach(n=>{if(n.nodeType===1&&n!==firstDirect(p,W,'pPr')&&!['bookmarkStart','bookmarkEnd','proofErr'].includes(n.localName))rm(n)});const r=wEl(p.ownerDocument,'r');if(base)r.appendChild(base);const t=wEl(p.ownerDocument,'t');if(/^\s|\s$/.test(text))t.setAttribute('xml:space','preserve');t.textContent=text;r.appendChild(t);p.appendChild(r);return true}
function isSeparator(t){return /^[-—_─━]{5,}$/.test(t.replace(/\s/g,''))}
function isCaptionText(t){return /^(图|表)\s*\d+\s+[^。；;]{1,120}$/.test(t.trim())}
function isChineseAuthor(t){const s=t.replace(/[＊*]/g,'').trim();if(s.length>120||!/[，,]/.test(s)||/[。；：]/.test(s))return false;const parts=s.split(/[，,]/).map(x=>x.trim()).filter(Boolean);return parts.length>=2&&parts.every(x=>/^[\u4e00-\u9fff·]{2,8}\d*$/.test(x))}
function isAffil(t){const s=t.trim();return /\d{6}/.test(s)&&/[\u4e00-\u9fff]/.test(s)&&(/^[（(]/.test(s)||/(大学|学院|医院|研究所|实验室|中心|公司|职业学院)/.test(s))}
function isEnAuthor(t){const s=t.trim();if(s.length>180||!/,/.test(s)||/[()]/.test(s)||/[。；:]/.test(s))return false;const parts=s.split(/[,，]/).map(x=>x.trim()).filter(Boolean);if(parts.length<2)return false;return parts.every(x=>/^(?:[A-Z][A-Z-]*|[A-Z][a-z-]+)\s+(?:[A-Z][A-Za-z-]*)(?:\s+[A-Z][A-Za-z-]*)?\d*$/.test(x))}
function isEnAffil(t){const s=t.trim();return /[A-Za-z]/.test(s)&&/(University|College|School|Institute|Hospital|China|Laboratory|Department|Company|Ltd|Technology)/i.test(s)&&/\d{5,6}/.test(s)}
function latinRatio(t){const a=(t.match(/[A-Za-z]/g)||[]).length,c=(t.match(/[\u4e00-\u9fff]/g)||[]).length;return a/(a+c+1)}
function classifyBody(body){const kinds=new Map();let titleSeen=false,cnAbs=false,enAbs=false,enKeys=false,inRefs=false,enTitleSeen=false;const ps=Array.from(body.childNodes).filter(n=>n.nodeType===1&&n.namespaceURI===W&&n.localName==='p');for(const p of ps){const t=visibleText(p);if(!t){kinds.set(p,'empty');continue}let k='body';if(/^收稿日期[:：]/.test(t))k='date';else if(/^基金项目[:：]/.test(t))k='fund';else if(/^摘\s*要[:：]/.test(t)){k='cnAbstract';cnAbs=true}else if(/^关键词[:：]/.test(t))k='cnKeywords';else if(/^中图分类号[:：]/.test(t))k='classLine';else if(/^Abstract[:：]/i.test(t)){k='enAbstract';enAbs=true}else if(/^(?:Keywords|Key\s*words)[:：]/i.test(t)){k='enKeywords';enKeys=true}else if(/^参考文献[:：]?\s*$/.test(t)){k='refHead';inRefs=true}else if(/^作者简介[:：]/.test(t)){k='authorBio';inRefs=false}else if(inRefs)k='reference';else if(isCaptionText(t))k='caption';else if(/^\d+\.\d+\.\d+\s*/.test(t))k='h3';else if(/^\d+\.\d+\s*/.test(t))k='h2';else if(/^\d+\s+/.test(t))k='h1';else if(!titleSeen&&!['date','fund'].includes(k)){k='title';titleSeen=true}else if(titleSeen&&!cnAbs){if(isChineseAuthor(t))k='author';else if(isAffil(t))k='affil'}else if(cnAbs&&!enAbs&&!enKeys){if(!enTitleSeen&&latinRatio(t)>.55&&t.length<360&&!isEnAuthor(t)&&!isEnAffil(t)){k='enTitle';enTitleSeen=true}else if(isEnAuthor(t))k='enAuthor';else if(isEnAffil(t))k='enAffil';else if(!enTitleSeen&&latinRatio(t)>.55&&t.length<360){k='enTitle';enTitleSeen=true}}kinds.set(p,k)}return kinds}
function findFirstTitle(body){for(const p of Array.from(body.childNodes).filter(n=>n.nodeType===1&&n.namespaceURI===W&&n.localName==='p')){const t=visibleText(p);if(t&&!/^收稿日期[:：]/.test(t)&&!/^基金项目[:：]/.test(t)&&!isSeparator(t))return p}return null}
function moveMetadata(body,stats){const ps=Array.from(body.childNodes).filter(n=>n.nodeType===1&&n.namespaceURI===W&&n.localName==='p');const date=ps.find(p=>/^收稿日期[:：]/.test(visibleText(p))),fund=ps.find(p=>/^基金项目[:：]/.test(visibleText(p))),title=findFirstTitle(body);if(!title)return;if(fund&&fund.nextSibling!==title){body.insertBefore(fund,title);stats.movedMeta++}if(date&&date.nextSibling!==(fund||title)){body.insertBefore(date,fund||title);stats.movedMeta++}}
function cleanSeparators(body,stats){for(const p of Array.from(body.childNodes).filter(n=>n.nodeType===1&&n.namespaceURI===W&&n.localName==='p'))if(isSeparator(visibleText(p))){rm(p);stats.removed++}}
function normCaptionText(t){const m=t.trim().match(/^(图|表)\s*(\d+)\s+(.+)$/);return m?`${m[1]}${m[2]}  ${m[3].trim().replace(/\s+/g,' ')}`:t.trim()}
function makeCaptionFromSource(src,text){const p=wEl(src.ownerDocument,'p'),pp=firstDirect(src,W,'pPr');if(pp)p.appendChild(pp.cloneNode(true));const r=wEl(src.ownerDocument,'r'),rp=cloneBaseRPr(src);if(rp)r.appendChild(rp);const t=wEl(src.ownerDocument,'t');t.textContent=text;r.appendChild(t);p.appendChild(r);setJc(p,'center');setInd(p,null);setSpacing(p);return p}
function splitEmbeddedCaptions(body,stats){const created=[];for(const p of Array.from(body.childNodes).filter(n=>n.nodeType===1&&n.namespaceURI===W&&n.localName==='p')){let txt=pText(p).replace(/\u00a0/g,' ');if(!txt.trim()||!isSimpleParagraph(p))continue;if(isCaptionText(txt)){const n=normCaptionText(txt);if(n!==txt.trim()){setPlainParagraphText(p,n);stats.textFixes++}created.push(p);continue}const re=/(^|\s{4,})((图|表)\s*(\d+)\s+.*?)(?=\s{4,}(?:图|表)\s*\d+\s+|$)/g;let m,spans=[],caps=[];while((m=re.exec(txt))){let c=m[2].trim();if(c.length>120||/[。；;]/.test(c))continue;const norm=normCaptionText(c);if(!isCaptionText(norm))continue;spans.push([m.index,m.index+m[0].length]);caps.push(norm)}if(!caps.length)continue;let residual='',pos=0;for(const [a,b] of spans){residual+=txt.slice(pos,a);pos=b}residual+=txt.slice(pos);residual=residual.trimEnd();const parent=p.parentNode;let marker=p;if(residual.trim()){setPlainParagraphText(p,residual);marker=p}else marker=p.previousSibling;let after=marker;for(const cap of caps){const np=makeCaptionFromSource(p,cap);if(after)parent.insertBefore(np,after.nextSibling);else parent.insertBefore(np,p);after=np;created.push(np);stats.captions++}if(!residual.trim())rm(p)}return created}
function captionMap(body){const fig=new Map(),tbl=new Map();for(const p of Array.from(body.childNodes).filter(n=>n.nodeType===1&&n.namespaceURI===W&&n.localName==='p')){const t=visibleText(p),m=t.match(/^(图|表)\s*(\d+)\s+[^。；;]{1,120}$/);if(m)(m[1]==='图'?fig:tbl).set(Number(m[2]),p)}return{fig,tbl}}
function containerOfDrawing(d){return Array.from(d.childNodes).find(n=>n.nodeType===1&&n.namespaceURI===WP&&(n.localName==='anchor'||n.localName==='inline'))||null}
function drawingX(c){if(!c||c.localName!=='anchor')return null;const ph=firstDirect(c,WP,'positionH'),po=ph&&firstDirect(ph,WP,'posOffset');return po?Number(po.textContent||0):null}
function convertAnchorToInline(d){const c=containerOfDrawing(d);if(!c||c.localName!=='anchor')return c;const doc=d.ownerDocument,inline=wpEl(doc,'inline');['distT','distB','distL','distR'].forEach(a=>inline.setAttribute(a,'0'));for(const n of ['extent','effectExtent','docPr','cNvGraphicFramePr']){const x=firstDirect(c,WP,n);if(x)inline.appendChild(x)}const gr=firstDirect(c,A,'graphic');if(gr)inline.appendChild(gr);d.replaceChild(inline,c);return inline}
function figureRecords(body){const ps=Array.from(body.childNodes).filter(n=>n.nodeType===1&&n.namespaceURI===W&&n.localName==='p'),rec=[];for(const p of ps){const sourceIndex=Array.from(body.childNodes).indexOf(p);for(const d of Array.from(p.getElementsByTagNameNS(W,'drawing'))){const c=containerOfDrawing(d);rec.push({p,d,c,anchor:!!c&&c.localName==='anchor',x:drawingX(c),sourceIndex})}}const ordered=[];for(let i=0;i<rec.length;){let g=[rec[i]],j=i+1;while(j<rec.length&&rec[j].sourceIndex-g[g.length-1].sourceIndex<=1){g.push(rec[j]);j++}if(g.length>1&&g.every(x=>x.anchor&&Number.isFinite(x.x)))g.sort((a,b)=>a.x-b.x);ordered.push(...g);i=j}ordered.forEach((r,i)=>r.num=i+1);return ordered}
function firstMention(body,num){for(const p of Array.from(body.childNodes).filter(n=>n.nodeType===1&&n.namespaceURI===W&&n.localName==='p')){const t=visibleText(p);if(!t||isCaptionText(t))continue;if(new RegExp(`图\\s*${num}(?!\\d)`).test(t))return p}return null}
function makeImageP(doc,drawing){const p=wEl(doc,'p');setJc(p,'center');setInd(p,null);setSpacing(p);const r=wEl(doc,'r');r.appendChild(drawing);p.appendChild(r);return p}
function isInBody(body,node){for(let n=node;n;n=n.parentNode)if(n===body)return true;return false}
function nextElement(n){let x=n&&n.nextSibling;while(x&&x.nodeType!==1)x=x.nextSibling;return x}
function prevElement(n){let x=n&&n.previousSibling;while(x&&x.nodeType!==1)x=x.previousSibling;return x}
function placeFigures(body,caps,stats){const rec=figureRecords(body);stats.figures=rec.length;for(const r of rec){const cap=caps.fig.get(r.num);if(r.anchor){convertAnchorToInline(r.d);const oldRun=r.d.parentNode;rm(oldRun);const ip=makeImageP(body.ownerDocument,r.d);if(cap&&cap.parentNode===body){body.insertBefore(ip,cap)}else{let target=firstMention(body,r.num);if(!target||!isInBody(body,target))target=r.p;if(target&&target.parentNode===body)body.insertBefore(ip,target.nextSibling);else body.insertBefore(ip,body.lastChild)}if(r.p.parentNode===body&&!visibleText(r.p)&&r.p.getElementsByTagNameNS(W,'drawing').length===0&&allRuns(r.p).every(x=>!pText(x)))rm(r.p);stats.anchorsFixed++}else{setJc(r.p,'center');setInd(r.p,null);setSpacing(r.p);if(cap&&cap.parentNode===body&&prevElement(cap)!==r.p&&r.p.parentNode===body)body.insertBefore(cap,r.p.nextSibling)}}}
function normalizeTable(tbl){let pr=firstDirect(tbl,W,'tblPr');if(!pr){pr=wEl(tbl.ownerDocument,'tblPr');tbl.insertBefore(pr,tbl.firstChild)}removeDirect(pr,'tblpPr');removeDirect(pr,'tblOverlap');let jc=firstDirect(pr,W,'jc');if(!jc){jc=wEl(tbl.ownerDocument,'jc');pr.appendChild(jc)}setW(jc,'val','center');for(const p of Array.from(tbl.getElementsByTagNameNS(W,'p'))){setParagraphFontDefault(p);for(const r of allRuns(p))setFont(r);setSpacing(p)}}
function placeTables(body,caps,stats){let n=0;for(const el of Array.from(body.childNodes)){if(el.nodeType===1&&el.namespaceURI===W&&el.localName==='tbl'){n++;normalizeTable(el);const cap=caps.tbl.get(n);if(cap&&cap.parentNode===body&&nextElement(cap)!==el)body.insertBefore(el,cap.nextSibling);stats.tables++}}}
function repairMathTypeNumbers(body,stats){let seq=0;for(const p of Array.from(body.getElementsByTagNameNS(W,'p'))){if(p.getElementsByTagNameNS(W,'object').length===0)continue;const instr=Array.from(p.getElementsByTagNameNS(W,'instrText')).map(x=>x.textContent||'').join(' ');if(!/SEQ\s+MTEqn/i.test(instr))continue;let num=null;for(const x of Array.from(p.getElementsByTagNameNS(W,'instrText'))){const v=(x.textContent||'').trim();if(/^\d+$/.test(v)){num=Number(v);break}}if(!num)num=++seq;else seq=Math.max(seq,num);const pp=firstDirect(p,W,'pPr');const objectRun=allRuns(p).find(r=>r.getElementsByTagNameNS(W,'object').length);if(!objectRun)continue;for(const n of Array.from(p.childNodes)){if(n.nodeType===1&&n!==pp&&n!==objectRun&&!['bookmarkStart','bookmarkEnd','proofErr'].includes(n.localName))rm(n)}const lead=wEl(p.ownerDocument,'r'),tab=wEl(p.ownerDocument,'tab');lead.appendChild(tab);p.insertBefore(lead,objectRun);const tail=wEl(p.ownerDocument,'r'),t=wEl(p.ownerDocument,'t');t.setAttribute('xml:space','preserve');t.textContent=`     （${num}）`;tail.appendChild(t);p.appendChild(tail);stats.formulas++;}}
function normalizeSections(doc,stats){for(const sp of Array.from(doc.getElementsByTagNameNS(W,'sectPr'))){let pgSz=firstDirect(sp,W,'pgSz');if(!pgSz){pgSz=wEl(doc,'pgSz');sp.appendChild(pgSz)}setW(pgSz,'w','11906');setW(pgSz,'h','16838');let mar=firstDirect(sp,W,'pgMar');if(!mar){mar=wEl(doc,'pgMar');sp.appendChild(mar)};setW(mar,'top','1440');setW(mar,'bottom','1440');setW(mar,'left','1800');setW(mar,'right','1800');setW(mar,'header','851');setW(mar,'footer','992');stats.sections++}}
function forcePartColorsBlack(doc){for(const c of Array.from(doc.getElementsByTagNameNS(W,'color')))setW(c,'val','000000')}
async function normalizeAuxParts(zip,stats){
 for(const name of ['word/styles.xml','word/numbering.xml']){
   const f=zip.file(name);if(!f)continue;
   const txt=await f.async('string'),d=new DOMParser().parseFromString(txt,'application/xml');
   if(d.getElementsByTagName('parsererror')[0])continue;
   forcePartColorsBlack(d);
   if(name==='word/numbering.xml'){
     for(const x of Array.from(d.getElementsByTagNameNS(W,'lvlText'))){
       const v=x.getAttributeNS(W,'val')||'';
       const m=v.match(/^[（(](%[1-9])[）)]$/);
       if(m){setW(x,'val',m[1]+'）');stats.numberingFixed++}
     }
     for(const lvl of Array.from(d.getElementsByTagNameNS(W,'lvl'))){
       let rp=firstDirect(lvl,W,'rPr');if(!rp){rp=wEl(d,'rPr');lvl.appendChild(rp)}
       let c=firstDirect(rp,W,'color');if(!c){c=wEl(d,'color');rp.appendChild(c)}setW(c,'val','000000')
     }
   }
   zip.file(name,new XMLSerializer().serializeToString(d));
 }
}
